In [1]:
import requests

url = "https://data.cityofnewyork.us/resource/erm2-nwe9.csv"
params = {
    "$where": "created_date >= '2025-01-01T00:00:00' AND created_date < '2026-01-01T00:00:00'",
    "$limit": 5000000,
}
r = requests.get(url, params=params)
with open("nyc311_2025.csv", "wb") as f:
    f.write(r.content)
print("done")

KeyboardInterrupt:

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv("nyc311_2025.csv")
df.shape

/tmp/ipykernel_16533/3794977759.py:5: DtypeWarning: Columns (0: incident_zip, 1: facility_type, 2: due_date, 3: taxi_company_borough, 4: road_ramp) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("nyc311_2025.csv")

(3655034, 44)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3655034 entries, 0 to 3655033
Data columns (total 44 columns):
 #   Column                          Dtype
---  ------                          -----
 0   unique_key                      int64
 1   created_date                    str
 2   closed_date                     str
 3   agency                          str
 4   agency_name                     str
 5   complaint_type                  str
 6   descriptor                      str
 7   descriptor_2                    str
 8   location_type                   str
 9   incident_zip                    object
 10  incident_address                str
 11  street_name                     str
 12  cross_street_1                  str
 13  cross_street_2                  str
 14  intersection_street_1           str
 15  intersection_street_2           str
 16  address_type                    str
 17  city                            str
 18  landmark                        str
 19  facility_type                   str
 20  status                          str
 21  due_date                        str
 22  resolution_description          str
 23  resolution_action_updated_date  str
 24  community_board                 str
 25  council_district                float64
 26  police_precinct                 str
 27  bbl                             float64
 28  borough                         str
 29  x_coordinate_state_plane        float64
 30  y_coordinate_state_plane        float64
 31  open_data_channel_type          str
 32  park_facility_name              str
 33  park_borough                    str
 34  vehicle_type                    str
 35  taxi_company_borough            str
 36  taxi_pick_up_location           str
 37  bridge_highway_name             str
 38  bridge_highway_direction        str
 39  road_ramp                       str
 40  bridge_highway_segment          str
 41  latitude                        float64
 42  longitude                       float64
 43  location                        str
dtypes: float64(6), int64(1), object(1), str(36)
memory usage: 1.2+ GB

In [6]:
(df.isnull().sum() / len(df) * 100).round(2).head(44)

unique_key                         0.00
created_date                       0.00
closed_date                        1.68
agency                             0.00
agency_name                        0.00
complaint_type                     0.00
descriptor                         2.31
descriptor_2                      61.86
location_type                     11.78
incident_zip                       0.82
incident_address                   3.36
street_name                        3.37
cross_street_1                    28.06
cross_street_2                    28.03
intersection_street_1             31.82
intersection_street_2             31.77
address_type                       0.39
city                               4.27
landmark                          38.55
facility_type                     99.68
status                             0.00
due_date                          99.55
resolution_description             2.01
resolution_action_updated_date     0.86
community_board                    0.00
council_district                   1.81
police_precinct                    0.00
bbl                               10.53
borough                            0.00
x_coordinate_state_plane           1.37
y_coordinate_state_plane           1.37
open_data_channel_type             0.00
park_facility_name                 0.14
park_borough                       0.00
vehicle_type                      95.68
taxi_company_borough              99.93
taxi_pick_up_location             99.03
bridge_highway_name               99.48
bridge_highway_direction          99.72
road_ramp                         99.76
bridge_highway_segment            99.48
latitude                           1.37
longitude                          1.37
location                           1.37
dtype: float64

In [4]:
df.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,...,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,67351762,2025-12-31T23:59:28.000,2026-01-01T00:40:32.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,Residential Building/House,10029.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.792141,-73.950097,POINT (-73.950097072847 40.792140506424)
1,67344624,2025-12-31T23:59:23.000,2026-01-01T01:03:42.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,Residential Building/House,10031.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.825137,-73.949447,POINT (-73.949447237231 40.82513729001)
2,67346873,2025-12-31T23:59:21.000,2026-01-01T00:58:13.000,NYPD,New York City Police Department,Blocked Driveway,Partial Access,NaN,Street/Sidewalk,11234.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.619995,-73.921167,POINT (-73.921167390534 40.619994693785)
3,67353004,2025-12-31T23:59:20.000,2026-01-01T00:57:31.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,Residential Building/House,11235.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.591542,-73.955979,POINT (-73.955979130812 40.591541524842)
4,67350526,2025-12-31T23:59:12.000,2026-01-01T00:41:16.000,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,NaN,Store/Commercial,10031.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.822593,-73.949525,POINT (-73.949525045155 40.822592971648)

In [4]:
df.tail()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,...,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
3655029,63586536,2025-01-01T00:00:34.000,2025-01-02T12:04:30.000,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,APARTMENT ONLY,NO HEAT,RESIDENTIAL BUILDING,10466.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.891940,-73.852775,POINT (-73.852775428009 40.891940075326)
3655030,63575612,2025-01-01T00:00:19.000,2025-01-01T00:43:08.000,NYPD,New York City Police Department,Illegal Fireworks,NaN,NaN,Street/Sidewalk,11230.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.629240,-73.968790,POINT (-73.968790430744 40.629239983687)
3655031,63581480,2025-01-01T00:00:17.000,2025-01-01T09:01:06.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,Residential Building/House,10466.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.891872,-73.860168,POINT (-73.860168452965 40.891872416493)
3655032,63584096,2025-01-01T00:00:13.000,2025-01-01T00:05:19.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,Residential Building/House,11211.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.711210,-73.958973,POINT (-73.958973315004 40.711209650263)
3655033,63577994,2025-01-01T00:00:12.000,2025-01-02T17:05:54.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,Residential Building/House,10466.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.891872,-73.860168,POINT (-73.860168452965 40.891872416493)

In [5]:
df['agency'].unique()

<StringArray>
[ 'NYPD',   'TLC',   'HPD',   'DOB',   'DOT',  'DSNY',  'DCWP',   'DEP',
   'DPR',   'EDC', 'DOHMH',   'OOS',   'DHS',   'DOE',   'OTI']
Length: 15, dtype: str

In [9]:
df['complaint_type'].unique()

<StringArray>
[       'Noise - Residential',           'Blocked Driveway',
         'Noise - Commercial',            'Illegal Parking',
          'Illegal Fireworks',    'Noise - Street/Sidewalk',
              'Lost Property',             'HEAT/HOT WATER',
                    'Boilers',     'Street Light Condition',
 ...
                   'Squeegee', 'Transfer Station Complaint',
                'Unspecified',         'Building Condition',
     'DEP Sidewalk Condition',  'Public Payphone Complaint',
      'DEP Highway Condition',              'DSNY Internal',
                   'Pet Shop',                   'ASBESTOS']
Length: 191, dtype: str

In [12]:
percentage_descriptor_nan = df['descriptor'].isna().mean() * 100
print(percentage_descriptor_nan)
percentage_descriptor2_nan = df['descriptor_2'].isna().mean() * 100
print(percentage_descriptor2_nan)

2.3062439364449143
61.864841749762114

In [18]:
pd.set_option('display.max_rows', None)
print(df['city'].value_counts().head(20))

city
BROOKLYN            1038523
BRONX                813320
NEW YORK             659686
STATEN ISLAND        126341
JAMAICA               85095
ASTORIA               61904
FLUSHING              60263
RIDGEWOOD             42930
CORONA                41833
FRESH MEADOWS         40386
QUEENS                39070
LONG ISLAND CITY      35443
FAR ROCKAWAY          27612
WOODSIDE              26543
MANHATTAN             26501
ELMHURST              24444
JACKSON HEIGHTS       23553
SOUTH OZONE PARK      22039
OZONE PARK            21728
EAST ELMHURST         20724
Name: count, dtype: int64

In [9]:
df['status'].value_counts()

status
Closed         3595036
In Progress      43588
Open              6561
Pending           4320
Assigned          4029
Started           1329
Unspecified        171
Name: count, dtype: int64

In [11]:
df['created_date'].dtype

In [12]:
df['borough'].value_counts()

borough
BROOKLYN         1078332
QUEENS            878212
BRONX             836525
MANHATTAN         725056
STATEN ISLAND     134302
Unspecified         2607
Name: count, dtype: int64

In [3]:
date_cols = ['created_date', 'closed_date']

df[date_cols] = df[date_cols].apply(pd.to_datetime)

In [7]:
df.created_date.dtype

dtype('<M8[us]')

In [5]:
df['unique_key'].duplicated().any()

np.False_

In [8]:
df['complaint_type'].value_counts()

complaint_type
Illegal Parking              577257
Noise - Residential          463349
HEAT/HOT WATER               315946
Noise - Street/Sidewalk      173049
Blocked Driveway             172723
                              ...
FHV Licensee Complaint            3
Building Marshal's Office         1
DEP Sidewalk Condition            1
DSNY Internal                     1
ASBESTOS                          1
Name: count, Length: 191, dtype: int64

In [5]:
df['closed_date'].isna().any()

np.True_

In [1]:
print("hi")

hi